name: TribesofDNA
favicon: null
layout_spectrum: 0.902872
typography_spectrum: 0.232264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0E0E0'
    - '#084858'
    - '#5890A8'
    - '#288898'
    - '#80C0D0'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
