name: TribesofDNA
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.232264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#012d76'
    - '#007dca'
    - '#fffff7'
    - '#526176'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
