typography_spectrum: 0.232264
color:
  brandColors:
    - '#000000'
    - '#012d76'
    - '#007dca'
    - '#fffff7'
    - '#526176'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25723
analytics:
  google: null
  facebook: null
  twitter: null
name: Tribes∞fDNA
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Northern Lights
    id: cbd86c10-2cba-4a2f-8a1b-6f57ea9d3861
    type: content
  - name: Full Moon
    id: c60eeaa5-8006-4ba0-94eb-2f88b2d2cc91
    type: content
favicon: null
title: We All Come From 0 ∞
purpose: []
