typography_spectrum: 0.232264
color:
  brandColors:
    - '#000000'
    - '#012d76'
    - '#007dca'
    - '#fffff7'
    - '#526176'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25723
analytics:
  google: null
  facebook: null
  twitter: null
name: TribesofDNA
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: We All Come From 0 ∞
purpose: []
