analytics: {}
color:
  brandColors:
    - '#C0E0E0'
    - '#084858'
    - '#5890A8'
    - '#288898'
    - '#80C0D0'
  brandStrength: 0.398649
  lightness: 0.401182
  rhythmicContrast: 0.337838
  saturation: 0.397804
cta: {}
layout_spectrum: 0.902872
name: TribesofDNA
opengraph: {}
purpose: {}
typography_spectrum: 0.232264
